import { FALLBACK_RANKINGS, KOREAN_NAMES, RANKING_CACHE_KEY } from "./ranking-data.js";

const API_ROOT = "https://api.fifa.com/api/v3";
const scheduleEndpoint = `${API_ROOT}/rankingschedules/all?type=0&gender=1&language=en`;
const HISTORY_KEY = "flag-country-quiz-football-history-v1";
const TRACK = { left: 34, right: 866, top: 20, bottom: 680 };
const TRACK_LENGTH = (TRACK.right - TRACK.left) * 20;
let cameraX = 0;
const PHASES = [
  { label: "예선 1경기", heat: true, target: 4 },
  { label: "예선 2경기", heat: true, target: 4 },
  { label: "예선 3경기", heat: true, target: 4 },
  { label: "예선 4경기", heat: true, target: 4 },
  { label: "16강", target: 8 }, { label: "8강", target: 4 },
  { label: "4강", target: 2 }, { label: "결승", target: 1 }
];
const canvas = document.querySelector("#race-canvas");
const ctx = canvas.getContext("2d");
const loading = document.querySelector("#canvas-loading");
const startButton = document.querySelector("#start-race");
const resetButton = document.querySelector("#reset-race");
const clearHistoryButton = document.querySelector("#clear-history");
const roundLabel = document.querySelector("#round-label");
const teamCount = document.querySelector("#team-count");
const raceStatus = document.querySelector("#race-status");
const raceMessage = document.querySelector("#race-message");
const standingsList = document.querySelector("#standings-list");
const historyList = document.querySelector("#history-list");
const lastUpdate = document.querySelector("#last-update");
let teams = [], activeTeams = [], heatGroups = [], heatQualified = [], phaseIndex = 0, race = null, animationId = null, lastFrame = 0;

function fetchJson(url) { return fetch(url, { headers: { Accept: "application/json" } }).then((r) => { if (!r.ok) throw new Error(`FIFA API ${r.status}`); return r.json(); }); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[c])); }
function flagUrl(code) { return `https://api.fifa.com/api/v1/picture/flags-sq-4/${String(code).toLowerCase()}`; }
function shuffle(items) { return [...items].sort(() => Math.random() - 0.5); }
function random(min, max) { return min + Math.random() * (max - min); }
function weekKey(date = new Date()) { const monday = new Date(date); const day = monday.getDay(); monday.setDate(monday.getDate() - (day === 0 ? 6 : day - 1)); monday.setHours(0, 0, 0, 0); return `${monday.getFullYear()}-${String(monday.getMonth() + 1).padStart(2, "0")}-${String(monday.getDate()).padStart(2, "0")}`; }
function readCachedRanking() { try { const cache = JSON.parse(localStorage.getItem(RANKING_CACHE_KEY) || "null"); return cache?.weekKey === weekKey() && cache.rows?.length ? cache : null; } catch { return null; } }
async function fetchFreshRanking() { const schedules = await fetchJson(scheduleEndpoint); const schedule = schedules.Results.filter((item) => item.Gender === 1).sort((a, b) => new Date(b.OfficialDate) - new Date(a.OfficialDate))[0]; if (!schedule) throw new Error("ranking schedule unavailable"); const data = await fetchJson(`${API_ROOT}/rankingsbyschedule?rankingScheduleId=${encodeURIComponent(schedule.IdRankingSchedule)}&language=en`); const rows = data.Results.filter((row) => row.StatusRanked !== 0 && row.Rank <= 100).sort((a, b) => a.Rank - b.Rank); const cache = { weekKey: weekKey(), savedAt: new Date().toISOString(), schedule, rows }; localStorage.setItem(RANKING_CACHE_KEY, JSON.stringify(cache)); return cache; }
function makeTeam(row) { const english = row.TeamName?.find((item) => item.Locale !== "ko-KR")?.Description || row.TeamName?.[0]?.Description || row.IdCountry; const name = row.TeamName?.find((item) => item.Locale === "ko-KR")?.Description || KOREAN_NAMES[english] || english; const image = new Image(); image.onload = () => { if (race) drawFrame(); else if (activeTeams.length) drawPreview(); }; image.src = flagUrl(row.IdCountry); return { rank: row.Rank, name, code: row.IdCountry, points: row.DecimalTotalPoints, image }; }
function laneY(index, count) { return TRACK.top + ((TRACK.bottom - TRACK.top) * (index + 0.5)) / count; }
function radiusFor(rank) { return 7 + ((Math.max(1, Math.min(100, rank)) - 1) / 99) * 7; }
function createObstacles() {
  const obstacles = [];
  for (let index = 0; index < 35; index += 1) {
    const x = TRACK.left + 150 + index * ((TRACK_LENGTH - 300) / 34) + random(-18, 18);
    obstacles.push({ type: index % 3 === 0 ? "spinner" : "diagonal", x, y: random(70, 630), length: random(70, 145), angle: random(-0.82, 0.82), width: 13, rotationSpeed: random(-2.8, 2.8), phase: random(0, 6) });
  }
  [0.08, 0.19, 0.31, 0.43, 0.55, 0.66, 0.76, 0.84, 0.91, 0.97].forEach((ratio, index) => obstacles.push({ type: "moving", x: TRACK.left + TRACK_LENGTH * ratio, baseY: random(90, 610), radius: 18, speed: random(1.1, 1.8), phase: index * 1.7 }));
  return obstacles;
}
function segment(o, time) { const angle = o.type === "spinner" ? o.angle + time * o.rotationSpeed : o.angle; const half = o.length / 2; return { angle, ax: o.x - Math.cos(angle) * half, ay: o.y - Math.sin(angle) * half, bx: o.x + Math.cos(angle) * half, by: o.y + Math.sin(angle) * half }; }
function closestPoint(px, py, ax, ay, bx, by) { const dx = bx - ax, dy = by - ay, len2 = dx * dx + dy * dy || 1; const t = Math.max(0, Math.min(1, ((px - ax) * dx + (py - ay) * dy) / len2)); return { x: ax + t * dx, y: ay + t * dy }; }
function resolveSegment(runner, obstacle, time) { const s = segment(obstacle, time); const p = closestPoint(runner.x, runner.y, s.ax, s.ay, s.bx, s.by); let nx = runner.x - p.x, ny = runner.y - p.y, dist = Math.hypot(nx, ny); const minDist = runner.radius + obstacle.width / 2; if (dist >= minDist) return; if (!dist) { nx = -Math.sin(s.angle); ny = Math.cos(s.angle); dist = 1; } nx /= dist; ny /= dist; runner.x += nx * (minDist - dist + 1.2); runner.y += ny * (minDist - dist + 1.2); const dot = runner.vx * nx + runner.vy * ny; if (obstacle.type === "diagonal") { const tx0 = Math.cos(s.angle), ty0 = Math.sin(s.angle); const tx = tx0 < 0 ? -tx0 : tx0, ty = tx0 < 0 ? -ty0 : ty0; const along = Math.max(62, runner.vx * tx + runner.vy * ty); runner.vx = tx * along; runner.vy = ty * along; runner.slide = 0.18; } else { if (dot < 0) { runner.vx -= 1.65 * dot * nx; runner.vy -= 1.65 * dot * ny; } runner.vx *= 0.92; runner.vy += ny * 70; runner.bounce = 0.28; } }
function resolveMoving(runner, obstacle, time) { const oy = obstacle.baseY + Math.sin(time * obstacle.speed + obstacle.phase) * 190; const dx = runner.x - obstacle.x, dy = runner.y - oy, dist = Math.hypot(dx, dy), minDist = runner.radius + obstacle.radius; if (dist >= minDist) return; const nx = dx / (dist || 1), ny = dy / (dist || 1); runner.x = obstacle.x + nx * (minDist + 0.8); runner.y = oy + ny * (minDist + 0.8); const dot = runner.vx * nx + runner.vy * ny; if (dot < 0) { runner.vx -= 1.8 * dot * nx; runner.vy -= 1.8 * dot * ny; } runner.vx *= 0.88; runner.vy *= 0.88; runner.bounce = 0.32; }
function drawBackground() { ctx.clearRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = "#fff"; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = "#526174"; ctx.font = "700 13px system-ui"; ctx.fillText("START", 8, 16); ctx.fillText("FINISH", canvas.width - 52, 16); }
function drawObstacle(o) { ctx.save(); ctx.lineCap = "round"; if (o.type === "moving") { const y = o.baseY + Math.sin((race?.elapsed || 0) * o.speed + o.phase) * 190; ctx.fillStyle = "#28384d"; ctx.beginPath(); ctx.arc(o.x, y, o.radius, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = "#efb53e"; ctx.lineWidth = 3; ctx.stroke(); } else { const s = segment(o, race?.elapsed || 0); ctx.strokeStyle = o.type === "spinner" ? "#cb3d4e" : "#35485d"; ctx.lineWidth = o.width; ctx.beginPath(); ctx.moveTo(s.ax, s.ay); ctx.lineTo(s.bx, s.by); ctx.stroke(); ctx.fillStyle = o.type === "spinner" ? "#7e2234" : "#172333"; ctx.beginPath(); ctx.arc(o.x, o.y, 7, 0, Math.PI * 2); ctx.fill(); } ctx.restore(); }
function drawRunner(runner) { const r = runner.radius; ctx.save(); ctx.beginPath(); ctx.arc(runner.x, runner.y, r, 0, Math.PI * 2); ctx.clip(); if (runner.image?.complete && runner.image.naturalWidth) ctx.drawImage(runner.image, runner.x - r, runner.y - r, r * 2, r * 2); else { ctx.fillStyle = "#d7dee8"; ctx.fillRect(runner.x - r, runner.y - r, r * 2, r * 2); } ctx.restore(); ctx.strokeStyle = runner.bounce > 0 ? "#f28b28" : runner.slide > 0 ? "#e2a51f" : "#1e2b3d"; ctx.lineWidth = runner.bounce > 0 || runner.slide > 0 ? 3 : 1.5; ctx.beginPath(); ctx.arc(runner.x, runner.y, r, 0, Math.PI * 2); ctx.stroke(); }
function drawFrame() { drawBackground(); if (!race) { ctx.save(); ctx.strokeStyle = "#182536"; ctx.lineWidth = 2; ctx.strokeRect(TRACK.left, TRACK.top, TRACK.right - TRACK.left, TRACK.bottom - TRACK.top); ctx.restore(); return; } const leader = race.runners.reduce((best, runner) => Math.max(best, runner.x), TRACK.left); cameraX = Math.max(0, Math.min(TRACK_LENGTH - canvas.width, leader - canvas.width * 0.28)); ctx.save(); ctx.translate(-cameraX, 0); ctx.strokeStyle = "#182536"; ctx.lineWidth = 2; ctx.strokeRect(TRACK.left, TRACK.top, TRACK_LENGTH, TRACK.bottom - TRACK.top); ctx.strokeStyle = "#17834b"; ctx.lineWidth = 4; ctx.beginPath(); ctx.moveTo(TRACK.left, TRACK.top); ctx.lineTo(TRACK.left, TRACK.bottom); ctx.stroke(); ctx.strokeStyle = "#d63d4f"; ctx.beginPath(); ctx.moveTo(TRACK.left + TRACK_LENGTH, TRACK.top); ctx.lineTo(TRACK.left + TRACK_LENGTH, TRACK.bottom); ctx.stroke(); race.obstacles.forEach(drawObstacle); race.runners.forEach(drawRunner); ctx.restore(); }
function startRound() { const phase = PHASES[phaseIndex], count = activeTeams.length; const runners = activeTeams.map((team, index) => ({ ...team, x: TRACK.left + 18, y: laneY(index, count), vx: random(85, 102) * (1 + (101 - team.rank) / 1100), vy: random(-3, 3), radius: radiusFor(team.rank), finished: false, slide: 0, bounce: 0 })); race = { runners, finishers: [], obstacles: createObstacles(), elapsed: 0, target: phase.target }; roundLabel.textContent = phase.heat ? `${phase.label} · 25개 팀` : phase.label; teamCount.textContent = count; raceStatus.textContent = "진행 중"; raceMessage.textContent = phase.heat ? "25개 팀이 실제 장애물을 통과하며 경쟁합니다. 상위 4팀이 진출합니다." : `${phase.label}에서 상위 ${phase.target}팀이 다음 라운드로 진출합니다.`; startButton.disabled = true; lastFrame = performance.now(); cancelAnimationFrame(animationId); animationId = requestAnimationFrame(tick); }
function tick(now) { if (!race) return; const dt = Math.min(0.04, Math.max(0.001, (now - lastFrame) / 1000)); lastFrame = now; race.elapsed += dt; race.runners.forEach((runner) => { if (runner.finished) return; runner.vx = Math.min(125, runner.vx + 8 * dt); runner.x += runner.vx * dt; runner.y += runner.vy * dt; runner.vy *= 0.995; race.obstacles.forEach((o) => o.type === "moving" ? resolveMoving(runner, o, race.elapsed) : resolveSegment(runner, o, race.elapsed)); if (runner.y < TRACK.top + runner.radius) { runner.y = TRACK.top + runner.radius; runner.vy = Math.abs(runner.vy) * .7; } if (runner.y > TRACK.bottom - runner.radius) { runner.y = TRACK.bottom - runner.radius; runner.vy = -Math.abs(runner.vy) * .7; } runner.slide = Math.max(0, runner.slide - dt); runner.bounce = Math.max(0, runner.bounce - dt); if (runner.x >= TRACK.left + TRACK_LENGTH - runner.radius) { runner.x = TRACK.left + TRACK_LENGTH - runner.radius; runner.finished = true; race.finishers.push(runner); } }); drawFrame(); if (race.finishers.length >= race.target) return completeRound(); animationId = requestAnimationFrame(tick); }
function renderStandings(list) { standingsList.innerHTML = list.slice(0, 16).map((team, index) => `<li><strong>${index + 1}</strong><img class="mini-flag" src="${flagUrl(team.code)}" alt=""><span>${escapeHtml(team.name)}</span><span class="rank-note">FIFA #${team.rank}</span></li>`).join(""); }
function completeRound() { cancelAnimationFrame(animationId); const phase = PHASES[phaseIndex], qualified = race.finishers.slice(0, phase.target); renderStandings(race.finishers); if (phase.heat) { heatQualified.push(...qualified); if (phaseIndex < 3) { phaseIndex += 1; activeTeams = heatGroups[phaseIndex]; startButton.disabled = false; startButton.dataset.continue = "true"; startButton.textContent = `${PHASES[phaseIndex].label} 시작`; raceStatus.textContent = "예선 완료"; raceMessage.textContent = `${qualified.map((team) => team.name).join(", ")} 진출 · 다음 25개 팀 경기를 시작하세요.`; return; } activeTeams = heatQualified; phaseIndex = 4; startButton.disabled = false; startButton.dataset.continue = "true"; startButton.textContent = "16강 시작"; raceStatus.textContent = "16강 진출"; raceMessage.textContent = "4회 예선에서 선발된 16개 팀이 결정되었습니다."; return; } activeTeams = qualified; if (phase.target === 1) { raceStatus.textContent = "우승"; raceMessage.textContent = `🏆 ${qualified[0].name}이(가) 최종 우승했습니다!`; saveHistory(qualified[0]); startButton.disabled = false; startButton.dataset.continue = "false"; startButton.textContent = "새 토너먼트"; return; } phaseIndex += 1; startButton.disabled = false; startButton.dataset.continue = "true"; startButton.textContent = `${PHASES[phaseIndex].label} 시작`; raceStatus.textContent = "라운드 완료"; raceMessage.textContent = `${phase.label} 완료 · 다음 라운드를 시작하세요.`; }
function saveHistory(winner) { const history = JSON.parse(localStorage.getItem(HISTORY_KEY) || "[]"); history.unshift({ date: new Date().toISOString(), winner: winner.name, rank: winner.rank }); localStorage.setItem(HISTORY_KEY, JSON.stringify(history.slice(0, 20))); renderHistory(); }
function renderHistory() { const history = JSON.parse(localStorage.getItem(HISTORY_KEY) || "[]"); historyList.innerHTML = history.length ? history.map((item) => `<li><span>${new Date(item.date).toLocaleString("ko-KR")}</span><strong>🏆 ${escapeHtml(item.winner)} <small>(FIFA #${item.rank})</small></strong></li>`).join("") : "<li>아직 기록이 없습니다.</li>"; }
function setupTournament() { const shuffled = shuffle(teams); heatGroups = [0, 1, 2, 3].map((index) => shuffled.slice(index * 25, (index + 1) * 25)); heatQualified = []; activeTeams = heatGroups[0]; phaseIndex = 0; race = null; startButton.dataset.continue = "false"; startButton.textContent = "예선 1경기 시작"; teamCount.textContent = 25; roundLabel.textContent = "예선 1경기 · 25개 팀"; raceStatus.textContent = "준비"; raceMessage.textContent = "100개 팀을 무작위 25개씩 나눈 첫 번째 경기입니다."; drawPreview(); }
function drawPreview() { drawBackground(); activeTeams.forEach((team, index) => drawRunner({ ...team, x: TRACK.left + 18, y: laneY(index, 25), radius: radiusFor(team.rank), slide: 0, bounce: 0 })); }
async function loadTeams() { const cached = readCachedRanking(); try { const ranking = cached || await fetchFreshRanking(); teams = ranking.rows.map(makeTeam); lastUpdate.textContent = new Date(ranking.schedule.OfficialDate).toLocaleDateString("ko-KR"); raceMessage.textContent = cached ? "이번 주 저장된 FIFA 랭킹을 사용합니다." : "이번 주 FIFA 랭킹을 저장했습니다."; } catch (error) { const schedule = { OfficialDate: "2026-07-20T00:00:00Z" }; localStorage.setItem(RANKING_CACHE_KEY, JSON.stringify({ weekKey: weekKey(), savedAt: new Date().toISOString(), schedule, rows: FALLBACK_RANKINGS })); teams = FALLBACK_RANKINGS.map(makeTeam); lastUpdate.textContent = new Date(schedule.OfficialDate).toLocaleDateString("ko-KR"); console.error(error); raceMessage.textContent = "FIFA API 연결 실패로 예비 랭킹을 사용합니다."; } loading.hidden = true; startButton.disabled = false; setupTournament(); }
startButton.addEventListener("click", () => { if (!teams.length) return; if (startButton.dataset.continue !== "true") setupTournament(); startRound(); });
resetButton.addEventListener("click", () => { cancelAnimationFrame(animationId); setupTournament(); standingsList.innerHTML = "<li>레이스를 시작하면 순위가 표시됩니다.</li>"; });
clearHistoryButton.addEventListener("click", () => { localStorage.removeItem(HISTORY_KEY); renderHistory(); });
renderHistory(); drawBackground(); loadTeams();
